# Generated by Django 3.0.7 on 2020-08-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_trabajo', models.CharField(max_length=300, verbose_name='Tipo de trabajo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_finalizacion', models.DateField(verbose_name='Fecha de finalizacion')),
                ('detalle', models.CharField(blank=True, max_length=500, null=True, verbose_name='Detalle de trabajo')),
                ('estado', models.CharField(max_length=50, verbose_name='Estadp de trabajo')),
            ],
        ),
    ]
