# Generated by Django 3.0.7 on 2020-08-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_auto_20200823_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_presupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('detalles', models.CharField(max_length=200, verbose_name='Detalles')),
            ],
        ),
    ]
