# Generated by Django 3.0.7 on 2020-08-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='empleado',
            name='dni',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(default='', max_length=200),
        ),
    ]
