# Generated by Django 3.0.7 on 2020-08-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_auto_20200823_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
