# Generated by Django 3.0.7 on 2020-08-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_auto_20200823_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.IntegerField(null=True),
        ),
    ]
