# Generated by Django 3.0.7 on 2020-08-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=220)),
                ('apellido', models.CharField(max_length=220)),
                ('direccion', models.CharField(max_length=220)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
    ]
