# Generated by Django 3.0.7 on 2020-08-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
