# Generated by Django 3.0.7 on 2020-08-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20200823_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motovehiculo',
            fields=[
                ('id_motovehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.IntegerField()),
                ('tipo_motovehiculo', models.CharField(max_length=200, verbose_name='Tipo del motovehiculo')),
                ('cilindrada', models.IntegerField()),
                ('trasmision', models.CharField(max_length=200, verbose_name='Trasmision del motovehiculo')),
                ('color', models.CharField(max_length=100, verbose_name='Color del motovehicuio')),
            ],
        ),
    ]
