# Generated by Django 3.0.7 on 2020-08-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_motovehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motovehiculo',
            name='patente',
            field=models.CharField(max_length=100, verbose_name='Patente'),
        ),
    ]
