# Generated by Django 3.0.7 on 2020-08-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20200825_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='motovehiculo',
            name='Marca',
            field=models.CharField(default='', max_length=100, verbose_name='Marca del motovehiculo'),
        ),
        migrations.AlterField(
            model_name='motovehiculo',
            name='color',
            field=models.CharField(default='', max_length=100, verbose_name='Color del motovehicuio'),
        ),
        migrations.AlterField(
            model_name='motovehiculo',
            name='patente',
            field=models.CharField(default='', max_length=100, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='motovehiculo',
            name='tipo_motovehiculo',
            field=models.CharField(default='', max_length=200, verbose_name='Tipo del motovehiculo'),
        ),
        migrations.AlterField(
            model_name='motovehiculo',
            name='trasmision',
            field=models.CharField(default='', max_length=200, verbose_name='Trasmision del motovehiculo'),
        ),
    ]
