# Generated by Django 3.0.7 on 2020-08-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.IntegerField()),
                ('categoria', models.CharField(max_length=250)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=250)),
            ],
        ),
    ]
