# Generated by Django 3.0.7 on 2020-08-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id_repuesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('stock', models.IntegerField(default=0)),
                ('categoria', models.CharField(max_length=200, verbose_name='categoria')),
            ],
        ),
    ]
