# Generated by Django 3.0.7 on 2020-08-23 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repuesto',
            options={'ordering': ['nombre'], 'verbose_name': 'Repuesto', 'verbose_name_plural': 'Repuestos'},
        ),
    ]
